---
- name: install prerequisite module
  apt: name=python-mysqldb state=present

- name: change root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: create db user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    priv: "{{ db_name }}.*:ALL"

- name: create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"