---
- name: Add key for extra MariaDB repository
  apt_key:
      id: "0xF1656F24C74CD1D8"
      keyserver: keyserver.ubuntu.com

- name: Add extra repository for MariaDB-10.2
  apt_repository: repo="deb [arch=amd64] http://mariadb.mirror.serveriai.lt/repo/10.2/ubuntu xenial main" state=present update_cache=yes

- name: Install MariaDB-server (10.2)
  apt: name="mariadb-server" state=present