#!/usr/bin/env ruby
# ^ Syntax hint

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.8.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # vagrant-hostmanager settings
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.hostname = "vm-stack-demo.dev"

  # vagrant-cachier settings
  if Vagrant.has_plugin?("vagrant-cachier") then
      config.cache.auto_detect = true
  end

  # Box configuration
  config.vm.box = 'bento/ubuntu-16.04'
  config.vm.box_check_update = false

  # Virtualbox specific configuration
  config.vm.provider :virtualbox do |vb, overrides|
    #vb.gui = true
    vb.customize [
      "modifyvm", :id,
      "--memory", "2028",
      "--name", "vm-stack-demo"
    ]

    # Network configuration
    overrides.vm.network :private_network, ip: "10.45.59.10"
    overrides.ssh.forward_agent = true

    # Shared folders
    mount_options = ["dmode=777", "fmode=777"]
    opts = if Vagrant::Util::Platform.windows?
      { :mount_options => mount_options }
    else
      { :nfs => mount_options }
    end

    overrides.vm.synced_folder(
      "../../",
      "/mnt/project",
      opts
    )
  end

  config.vm.provision :ansible_local do |ansible|
      ansible.install_mode = "pip"
      ansible.playbook = "/mnt/project/tools/ansible/playbook.yml"
      ansible.inventory_path = "/mnt/project/tools/ansible/inventory/dev"
      ansible.verbose = "v"
      ansible.vault_password_file = "/mnt/project/tools/ansible/.vault-secret-key"
  end
end
