#!/usr/bin/env ruby
# ^ Syntax hint
require 'ffi'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # vagrant-hostsupdater settings
  config.vm.hostname = "vm-stack-demo.dev"

  # vagrant-cachier settings
  config.cache.auto_detect = true

  # Box configuration
  config.vm.box = 'ubuntu/trusty64'
  config.vm.box_check_update = false

  # Virtualbox specific configuration
  config.vm.provider :virtualbox do |vb, overrides|
    #vb.gui = true
    vb.customize [
      "modifyvm", :id,
      "--memory", "2028",
      "--name", "vm-stack-demo"
    ]

    # Network configuration
    overrides.vm.network :private_network, ip: "10.45.59.10"
    overrides.ssh.forward_agent = true

    # Shared folders
    mount_options = ["dmode=777", "fmode=777"]
    opts = if FFI::Platform::IS_WINDOWS
      { :mount_options => mount_options }
    elsif FFI::Platform::IS_LINUX
      { :nfs => mount_options, :nfs_version => 4, :nfs_udp => false }
    else
      { :nfs => mount_options }
    end

    overrides.vm.synced_folder(
      "../../",
      "/mnt/project",
      opts
    )
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
    ansible.inventory_path = "../ansible/inventory/dev"
    ansible.verbose = "v"
    ansible.vault_password_file = "../ansible/.vault-secret-key"
  end
end
