---
- include: nginx.yml

- include: php7.yml

- include: postfix.yml

- include: vhost.yml

- name: link webroot
  file: src=/mnt/project/code dest="/var/www/{{ host_name }}" state=link

- include: app_config.yml

- name: restart nginx
  service: name=nginx state=restarted

- name: restart php-fpm
  service: name=php7.1-fpm state=restarted