---
- name: add PPA repository for php7.0
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: Install php7.0
  apt: name=php7.0 state=present

- name: Install php7.0-fpm
  apt: name=php7.0-fpm state=present

- name: Install php7.0-curl
  apt: name=php7.0-curl state=present

- name: Install php7.0-gd
  apt: name=php7.0-gd state=present

- name: Install php7.0-mcrypt
  apt: name=php7.0-mcrypt state=present

- name: Install php7.0-intl
  apt: name=php7.0-intl state=present

- name: Install php7.0-mysql
  apt: name=php7.0-mysql state=present